# Generated by Django 5.1 on 2024-08-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("archived", "Archived")],
                default="active",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(default="general", max_length=50),
        ),
        migrations.AddField(
            model_name="week",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
